import { Captions, Check, Clapperboard, FileCheck2, FileVideo, HardDrive, LockKeyhole, Scissors, WifiOff } from 'lucide-react';

const steps=[
  [FileVideo,'1. Video laden','MP4, MOV, MKV oder WebM bis zu 8 Stunden auswählen.'],
  [Scissors,'2. Stellen schneiden','Starke Passagen übernehmen oder den Bereich selbst setzen.'],
  [Captions,'3. Fertig exportieren','Format, Reaction-Layout und Untertitel wählen.'],
] as const;

const privacyItems = [
  [HardDrive,'01','Geschützt verarbeitet','Video, Transkript und Render sind eindeutig deinem Konto zugeordnet.'],
  [WifiOff,'02','Eigener Videodienst','Die Kernfunktionen laufen über den geschützten ClipForge-Dienst.'],
  [FileCheck2,'03','Für lange Produktionen','MP4, MOV, MKV und WebM bis 8 Stunden – bereit für Reels, Shorts und YouTube.'],
  [LockKeyhole,'04','Sicherheitsprotokoll','Bei angemeldeter Nutzung werden Account, IP-Adresse, Zeitpunkt und Bereich protokolliert und nach spätestens 24 Stunden gelöscht.'],
] as const;

export function SiteInfo(){return <>
  <section id="how-it-works" className="bg-ink px-4 py-16 text-white sm:px-6 sm:py-20 lg:px-10 lg:py-24"><div className="mx-auto max-w-[1240px]"><p className="text-[10px] font-extrabold tracking-[.17em] text-mint">EIN KLARER ABLAUF</p><div className="mt-4 grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><h2 className="text-[clamp(2.6rem,5vw,5rem)] font-semibold leading-[.92] tracking-[-.055em]">Vom langen Video zum fertigen Clip.</h2><p className="max-w-xl text-sm leading-7 text-white/60 lg:justify-self-end">Keine überladene Oberfläche. Jeder Schritt baut auf dem vorherigen auf und führt direkt zur Vorschau und zum Export.</p></div><div className="mt-10 grid gap-3 md:grid-cols-3">{steps.map(([Icon,title,text])=><article key={title} className="rounded-[22px] border border-white/10 bg-white/[.055] p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-mint text-ink"><Icon size={18}/></span><h3 className="mt-5 text-sm font-bold">{title}</h3><p className="mt-2 text-xs leading-5 text-white/55">{text}</p></article>)}</div></div></section>
  <section id="privacy" className="bg-mint/30 px-4 py-16 sm:px-6 sm:py-20 lg:px-10"><div className="mx-auto max-w-[1240px] overflow-hidden rounded-[28px] border border-ink/[.08] bg-white shadow-[0_18px_55px_rgba(32,20,46,.07)]"><div className="grid lg:grid-cols-[.78fr_1.22fr]"><div className="border-b border-ink/[.07] p-7 sm:p-10 lg:border-b-0 lg:border-r lg:p-12"><span className="grid h-11 w-11 place-items-center rounded-[14px] bg-ink text-mint"><LockKeyhole size={19}/></span><p className="mt-7 text-[9px] font-extrabold tracking-[.18em] text-purple">PRIVATE BY DESIGN</p><h2 className="mt-3 text-4xl font-semibold leading-[.96] tracking-[-.045em] sm:text-5xl">Dein Material.<br/>Dein Projekt.</h2><p className="mt-5 max-w-sm text-sm leading-6 text-muted">Du kontrollierst den kompletten Workflow – vom geschützten Upload bis zum fertigen Export.</p></div><div className="divide-y divide-ink/[.07]">{privacyItems.map(([Icon,number,title,text])=><article key={number} className="group grid gap-4 p-6 transition-colors hover:bg-cream/55 sm:grid-cols-[44px_1fr_auto] sm:items-center sm:px-8"><span className="grid h-11 w-11 place-items-center rounded-[13px] bg-cream text-purple transition-colors group-hover:bg-ink group-hover:text-mint"><Icon size={18}/></span><div><span className="text-[8px] font-extrabold tracking-[.16em] text-muted">{number}</span><h3 className="mt-1 text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted">{text}</p></div><Check size={16} className="hidden text-[#248c69] sm:block"/></article>)}</div></div></div></section>
  <footer className="border-t border-ink/[.08] bg-cream px-4 py-8 sm:px-6 lg:px-10"><div className="mx-auto flex max-w-[1240px] flex-col gap-5 text-xs text-muted sm:flex-row sm:items-center sm:justify-between"><a href="#top" className="flex items-center gap-2 font-bold text-ink"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-ink text-white"><Clapperboard size={15}/></span>ClipForge Cutter</a><div className="flex flex-wrap gap-5"><a href="#privacy" className="hover:text-ink">Datenschutz</a><a href="#how-it-works" className="hover:text-ink">Funktionsweise</a><a href="#examples" className="hover:text-ink">Beispiele</a></div><span>Dein Video-Werkzeug</span></div></footer>
  </>}
